#! /bin/sh

xsetroot -cursor_name left_ptr

# AutoStart
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
$HOME/.config/polybar/launch.sh

feh --bg-fill /home/oskar/Pictures/Wallpaper.jpg

# Configs
if type "xrandr"; then
    for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do        
        OPTIONS=$(xrandr --query | grep $m | cut -d" " -f1,3,4 | cut -d"+" -f1)
        RESP=$( echo ${OPTIONS} | cut -d" " -f3)
        RES=$( echo ${OPTIONS} | cut -d" " -f2)
        if [ "$RES" = "primary" ]; then
            xrandr --output $m --primary --mode $RESP --rotate normal
        else
            xrandr --output $m --mode $RES --rotate normal
        fi
        bspc monitor $m -d V VI VII VIII
    done
#else
#    echo "\ndet funkar inte\n"
#    xrandr --output HDMI-2 --off
#    while bspc node @V: --kill; do
#        :
#    done
#    while bspc node @VI: --kill; do
#        :
#    done
#    while bspc node @VII: --kill; do
#        :
#    done
#    while bspc node @VIII: --kill; do
#        :
#    done
#
#    bspc desktop -r V VI VII VIII
#    bspc monitor HDMI-2 -r
fi

bspc config border_width         2 
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config automatic_scheme spiral



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

